import { GetServerSideProps } from 'next';
import { useSession } from 'next-auth/react';
import { signIn, signOut } from 'next-auth/react';
import prisma from '@/utils/prisma';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Home() {
	const session = useSession();
	console.log(session);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<div>
					<h1>CAMPER SITE</h1>
					<Link href='/inventory'>Invent</Link>
				</div>
				<div>
					<button onClick={() => signIn()}>SIGN in</button>
					<button onClick={() => signOut()}>SIGN OUT</button>
					<div>{session.data?.user?.name}</div>
				</div>
			</main>
		</>
	);
}

export const getServerSideProps: GetServerSideProps = async () => {
	const user = await prisma.user.findFirst({
		include: { orders: { include: { items: true } } },
	});
	const data = 'hello';
	return { props: { name: data } };
};
